version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: semantic_search_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

  chromadb:
    image: chromadb/chroma:latest
    container_name: chromadb
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/chroma
    restart: always

volumes:
  mongo_data:
  chroma_data:
